<?php if (!defined('ASSETS_FOLDER')) { define('ASSETS_FOLDER', './'); } ?>
<div class="emoticons">
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/s1.png" onclick="insertEmoticon('[:s1:]')" title="[:s1:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/s10.png" onclick="insertEmoticon('[:s10:]')" title="[:s10:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/s11.png" onclick="insertEmoticon('[:s11:]')" title="[:s11:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/s12.png" onclick="insertEmoticon('[:s12:]')" title="[:s12:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/s13.png" onclick="insertEmoticon('[:s13:]')" title="[:s13:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/s14.png" onclick="insertEmoticon('[:s14:]')" title="[:s14:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/s15.png" onclick="insertEmoticon('[:s15:]')" title="[:s15:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/s16.png" onclick="insertEmoticon('[:s16:]')" title="[:s16:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/s17.png" onclick="insertEmoticon('[:s17:]')" title="[:s17:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/s18.png" onclick="insertEmoticon('[:s18:]')" title="[:s18:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/s19.png" onclick="insertEmoticon('[:s19:]')" title="[:s19:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/s2.png" onclick="insertEmoticon('[:s2:]')" title="[:s2:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/s20.png" onclick="insertEmoticon('[:s20:]')" title="[:s20:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/s21.png" onclick="insertEmoticon('[:s21:]')" title="[:s21:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/s22.png" onclick="insertEmoticon('[:s22:]')" title="[:s22:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/s23.png" onclick="insertEmoticon('[:s23:]')" title="[:s23:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/s24.png" onclick="insertEmoticon('[:s24:]')" title="[:s24:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/s25.png" onclick="insertEmoticon('[:s25:]')" title="[:s25:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/s26.png" onclick="insertEmoticon('[:s26:]')" title="[:s26:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/s27.png" onclick="insertEmoticon('[:s27:]')" title="[:s27:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/s28.png" onclick="insertEmoticon('[:s28:]')" title="[:s28:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/s29.png" onclick="insertEmoticon('[:s29:]')" title="[:s29:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/s3.png" onclick="insertEmoticon('[:s3:]')" title="[:s3:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/s30.png" onclick="insertEmoticon('[:s30:]')" title="[:s30:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/s4.png" onclick="insertEmoticon('[:s4:]')" title="[:s4:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/s5.png" onclick="insertEmoticon('[:s5:]')" title="[:s5:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/s6.png" onclick="insertEmoticon('[:s6:]')" title="[:s6:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/s7.png" onclick="insertEmoticon('[:s7:]')" title="[:s7:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/s8.png" onclick="insertEmoticon('[:s8:]')" title="[:s8:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/smileys/s9.png" onclick="insertEmoticon('[:s9:]')" title="[:s9:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c10.gif" onclick="insertEmoticon('[:c10:]')" title="[:c10:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c11.gif" onclick="insertEmoticon('[:c11:]')" title="[:c11:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c12.gif" onclick="insertEmoticon('[:c12:]')" title="[:c12:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c13.gif" onclick="insertEmoticon('[:c13:]')" title="[:c13:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c14.gif" onclick="insertEmoticon('[:c14:]')" title="[:c14:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c15.gif" onclick="insertEmoticon('[:c15:]')" title="[:c15:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c16.gif" onclick="insertEmoticon('[:c16:]')" title="[:c16:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c17.gif" onclick="insertEmoticon('[:c17:]')" title="[:c17:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c18.gif" onclick="insertEmoticon('[:c18:]')" title="[:c18:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c19.gif" onclick="insertEmoticon('[:c19:]')" title="[:c19:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c2.gif" onclick="insertEmoticon('[:c2:]')" title="[:c2:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c20.gif" onclick="insertEmoticon('[:c20:]')" title="[:c20:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c21.gif" onclick="insertEmoticon('[:c21:]')" title="[:c21:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c22.gif" onclick="insertEmoticon('[:c22:]')" title="[:c22:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c23.gif" onclick="insertEmoticon('[:c23:]')" title="[:c23:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c24.gif" onclick="insertEmoticon('[:c24:]')" title="[:c24:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c25.gif" onclick="insertEmoticon('[:c25:]')" title="[:c25:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c26.gif" onclick="insertEmoticon('[:c26:]')" title="[:c26:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c27.gif" onclick="insertEmoticon('[:c27:]')" title="[:c27:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c28.gif" onclick="insertEmoticon('[:c28:]')" title="[:c28:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c29.gif" onclick="insertEmoticon('[:c29:]')" title="[:c29:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c3.gif" onclick="insertEmoticon('[:c3:]')" title="[:c3:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c30.gif" onclick="insertEmoticon('[:c30:]')" title="[:c30:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c31.gif" onclick="insertEmoticon('[:c31:]')" title="[:c31:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c32.gif" onclick="insertEmoticon('[:c32:]')" title="[:c32:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c33.gif" onclick="insertEmoticon('[:c33:]')" title="[:c33:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c34.gif" onclick="insertEmoticon('[:c34:]')" title="[:c34:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c35.gif" onclick="insertEmoticon('[:c35:]')" title="[:c35:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c36.gif" onclick="insertEmoticon('[:c36:]')" title="[:c36:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c37.gif" onclick="insertEmoticon('[:c37:]')" title="[:c37:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c38.gif" onclick="insertEmoticon('[:c38:]')" title="[:c38:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c39.gif" onclick="insertEmoticon('[:c39:]')" title="[:c39:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c4.gif" onclick="insertEmoticon('[:c4:]')" title="[:c4:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c40.gif" onclick="insertEmoticon('[:c40:]')" title="[:c40:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c41.gif" onclick="insertEmoticon('[:c41:]')" title="[:c41:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c42.gif" onclick="insertEmoticon('[:c42:]')" title="[:c42:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c43.gif" onclick="insertEmoticon('[:c43:]')" title="[:c43:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c44.gif" onclick="insertEmoticon('[:c44:]')" title="[:c44:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c45.gif" onclick="insertEmoticon('[:c45:]')" title="[:c45:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c46.gif" onclick="insertEmoticon('[:c46:]')" title="[:c46:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c47.gif" onclick="insertEmoticon('[:c47:]')" title="[:c47:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c48.gif" onclick="insertEmoticon('[:c48:]')" title="[:c48:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c49.gif" onclick="insertEmoticon('[:c49:]')" title="[:c49:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c5.gif" onclick="insertEmoticon('[:c5:]')" title="[:c5:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c50.gif" onclick="insertEmoticon('[:c50:]')" title="[:c50:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c51.gif" onclick="insertEmoticon('[:c51:]')" title="[:c51:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c52.gif" onclick="insertEmoticon('[:c52:]')" title="[:c52:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c53.gif" onclick="insertEmoticon('[:c53:]')" title="[:c53:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c54.gif" onclick="insertEmoticon('[:c54:]')" title="[:c54:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c55.gif" onclick="insertEmoticon('[:c55:]')" title="[:c55:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c6.gif" onclick="insertEmoticon('[:c6:]')" title="[:c6:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c7.gif" onclick="insertEmoticon('[:c7:]')" title="[:c7:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c8.gif" onclick="insertEmoticon('[:c8:]')" title="[:c8:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/cutes/c9.gif" onclick="insertEmoticon('[:c9:]')" title="[:c9:]" />
</div>