<?php if (!defined('ASSETS_FOLDER')) { define('ASSETS_FOLDER', './'); } ?>
<div class="emoticons">
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o0.gif" onclick="insertEmoticon('[:o0:]')" title="[:o0:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o1.gif" onclick="insertEmoticon('[:o1:]')" title="[:o1:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o10.gif" onclick="insertEmoticon('[:o10:]')" title="[:o10:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o100.gif" onclick="insertEmoticon('[:o100:]')" title="[:o100:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o101.gif" onclick="insertEmoticon('[:o101:]')" title="[:o101:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o102.gif" onclick="insertEmoticon('[:o102:]')" title="[:o102:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o103.gif" onclick="insertEmoticon('[:o103:]')" title="[:o103:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o104.gif" onclick="insertEmoticon('[:o104:]')" title="[:o104:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o105.gif" onclick="insertEmoticon('[:o105:]')" title="[:o105:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o106.gif" onclick="insertEmoticon('[:o106:]')" title="[:o106:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o107.gif" onclick="insertEmoticon('[:o107:]')" title="[:o107:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o108.gif" onclick="insertEmoticon('[:o108:]')" title="[:o108:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o109.gif" onclick="insertEmoticon('[:o109:]')" title="[:o109:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o11.gif" onclick="insertEmoticon('[:o11:]')" title="[:o11:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o12.gif" onclick="insertEmoticon('[:o12:]')" title="[:o12:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o13.gif" onclick="insertEmoticon('[:o13:]')" title="[:o13:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o14.gif" onclick="insertEmoticon('[:o14:]')" title="[:o14:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o15.gif" onclick="insertEmoticon('[:o15:]')" title="[:o15:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o16.gif" onclick="insertEmoticon('[:o16:]')" title="[:o16:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o17.gif" onclick="insertEmoticon('[:o17:]')" title="[:o17:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o18.gif" onclick="insertEmoticon('[:o18:]')" title="[:o18:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o19.gif" onclick="insertEmoticon('[:o19:]')" title="[:o19:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o2.gif" onclick="insertEmoticon('[:o2:]')" title="[:o2:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o20.gif" onclick="insertEmoticon('[:o20:]')" title="[:o20:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o21.gif" onclick="insertEmoticon('[:o21:]')" title="[:o21:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o22.gif" onclick="insertEmoticon('[:o22:]')" title="[:o22:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o23.gif" onclick="insertEmoticon('[:o23:]')" title="[:o23:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o24.gif" onclick="insertEmoticon('[:o24:]')" title="[:o24:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o25.gif" onclick="insertEmoticon('[:o25:]')" title="[:o25:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o26.gif" onclick="insertEmoticon('[:o26:]')" title="[:o26:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o27.gif" onclick="insertEmoticon('[:o27:]')" title="[:o27:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o28.gif" onclick="insertEmoticon('[:o28:]')" title="[:o28:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o29.gif" onclick="insertEmoticon('[:o29:]')" title="[:o29:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o3.gif" onclick="insertEmoticon('[:o3:]')" title="[:o3:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o30.gif" onclick="insertEmoticon('[:o30:]')" title="[:o30:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o31.gif" onclick="insertEmoticon('[:o31:]')" title="[:o31:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o32.gif" onclick="insertEmoticon('[:o32:]')" title="[:o32:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o33.gif" onclick="insertEmoticon('[:o33:]')" title="[:o33:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o34.gif" onclick="insertEmoticon('[:o34:]')" title="[:o34:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o35.gif" onclick="insertEmoticon('[:o35:]')" title="[:o35:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o36.gif" onclick="insertEmoticon('[:o36:]')" title="[:o36:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o37.gif" onclick="insertEmoticon('[:o37:]')" title="[:o37:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o38.gif" onclick="insertEmoticon('[:o38:]')" title="[:o38:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o39.gif" onclick="insertEmoticon('[:o39:]')" title="[:o39:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o4.gif" onclick="insertEmoticon('[:o4:]')" title="[:o4:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o40.gif" onclick="insertEmoticon('[:o40:]')" title="[:o40:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o41.gif" onclick="insertEmoticon('[:o41:]')" title="[:o41:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o42.gif" onclick="insertEmoticon('[:o42:]')" title="[:o42:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o43.gif" onclick="insertEmoticon('[:o43:]')" title="[:o43:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o44.gif" onclick="insertEmoticon('[:o44:]')" title="[:o44:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o45.gif" onclick="insertEmoticon('[:o45:]')" title="[:o45:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o46.gif" onclick="insertEmoticon('[:o46:]')" title="[:o46:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o47.gif" onclick="insertEmoticon('[:o47:]')" title="[:o47:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o48.gif" onclick="insertEmoticon('[:o48:]')" title="[:o48:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o49.gif" onclick="insertEmoticon('[:o49:]')" title="[:o49:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o5.gif" onclick="insertEmoticon('[:o5:]')" title="[:o5:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o51.gif" onclick="insertEmoticon('[:o51:]')" title="[:o51:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o52.gif" onclick="insertEmoticon('[:o52:]')" title="[:o52:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o53.gif" onclick="insertEmoticon('[:o53:]')" title="[:o53:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o54.gif" onclick="insertEmoticon('[:o54:]')" title="[:o54:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o55.gif" onclick="insertEmoticon('[:o55:]')" title="[:o55:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o56.gif" onclick="insertEmoticon('[:o56:]')" title="[:o56:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o57.gif" onclick="insertEmoticon('[:o57:]')" title="[:o57:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o58.gif" onclick="insertEmoticon('[:o58:]')" title="[:o58:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o59.gif" onclick="insertEmoticon('[:o59:]')" title="[:o59:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o6.gif" onclick="insertEmoticon('[:o6:]')" title="[:o6:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o60.gif" onclick="insertEmoticon('[:o60:]')" title="[:o60:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o61.gif" onclick="insertEmoticon('[:o61:]')" title="[:o61:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o62.gif" onclick="insertEmoticon('[:o62:]')" title="[:o62:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o63.gif" onclick="insertEmoticon('[:o63:]')" title="[:o63:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o64.gif" onclick="insertEmoticon('[:o64:]')" title="[:o64:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o65.gif" onclick="insertEmoticon('[:o65:]')" title="[:o65:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o66.gif" onclick="insertEmoticon('[:o66:]')" title="[:o66:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o67.gif" onclick="insertEmoticon('[:o67:]')" title="[:o67:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o68.gif" onclick="insertEmoticon('[:o68:]')" title="[:o68:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o69.gif" onclick="insertEmoticon('[:o69:]')" title="[:o69:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o7.gif" onclick="insertEmoticon('[:o7:]')" title="[:o7:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o70.gif" onclick="insertEmoticon('[:o70:]')" title="[:o70:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o71.gif" onclick="insertEmoticon('[:o71:]')" title="[:o71:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o72.gif" onclick="insertEmoticon('[:o72:]')" title="[:o72:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o73.gif" onclick="insertEmoticon('[:o73:]')" title="[:o73:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o74.gif" onclick="insertEmoticon('[:o74:]')" title="[:o74:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o75.gif" onclick="insertEmoticon('[:o75:]')" title="[:o75:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o76.gif" onclick="insertEmoticon('[:o76:]')" title="[:o76:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o77.gif" onclick="insertEmoticon('[:o77:]')" title="[:o77:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o78.gif" onclick="insertEmoticon('[:o78:]')" title="[:o78:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o79.gif" onclick="insertEmoticon('[:o79:]')" title="[:o79:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o8.gif" onclick="insertEmoticon('[:o8:]')" title="[:o8:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o80.gif" onclick="insertEmoticon('[:o80:]')" title="[:o80:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o81.gif" onclick="insertEmoticon('[:o81:]')" title="[:o81:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o82.gif" onclick="insertEmoticon('[:o82:]')" title="[:o82:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o83.gif" onclick="insertEmoticon('[:o83:]')" title="[:o83:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o84.gif" onclick="insertEmoticon('[:o84:]')" title="[:o84:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o85.gif" onclick="insertEmoticon('[:o85:]')" title="[:o85:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o86.gif" onclick="insertEmoticon('[:o86:]')" title="[:o86:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o87.gif" onclick="insertEmoticon('[:o87:]')" title="[:o87:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o88.gif" onclick="insertEmoticon('[:o88:]')" title="[:o88:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o89.gif" onclick="insertEmoticon('[:o89:]')" title="[:o89:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o9.gif" onclick="insertEmoticon('[:o9:]')" title="[:o9:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o90.gif" onclick="insertEmoticon('[:o90:]')" title="[:o90:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o91.gif" onclick="insertEmoticon('[:o91:]')" title="[:o91:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o92.gif" onclick="insertEmoticon('[:o92:]')" title="[:o92:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o93.gif" onclick="insertEmoticon('[:o93:]')" title="[:o93:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o94.gif" onclick="insertEmoticon('[:o94:]')" title="[:o94:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o95.gif" onclick="insertEmoticon('[:o95:]')" title="[:o95:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o96.gif" onclick="insertEmoticon('[:o96:]')" title="[:o96:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o97.gif" onclick="insertEmoticon('[:o97:]')" title="[:o97:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o98.gif" onclick="insertEmoticon('[:o98:]')" title="[:o98:]" />
<img src="<?php echo ASSETS_FOLDER; ?>img/onionclub/o99.gif" onclick="insertEmoticon('[:o99:]')" title="[:o99:]" />

<div style="padding-top:10px;" class="muted">
<small>&copy; Ethan Liu (Taiwanese artist) at emstudio under <a href="http://creativecommons.org/licenses/by/3.0/" target="_blank">CC BY 3.0</a></small>
</div>

</div>